# Generated by Django 3.2.9 on 2021-11-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20211128_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrybus',
            name='bus',
        ),
    ]
