# Generated by Django 3.2.9 on 2021-11-28 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_carrybus_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrybus',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.bus'),
            preserve_default=False,
        ),
    ]
